#!/bin/bash

docsets=~/DocSets # output dir
frameworkPath=. # just call it from inside Redbeard.framework/
iconPath=../ # path for the icon.png and icon@2.png
appledocTemplateDir=~/Library/Application\ Support/appledoc # check this, it's not there if you used brew to install appledocs

usage() {
   echo "Usage:"
   echo " `basename $0` version"
}

# version must be provided
if [ $# -lt 1 ]; then usage && exit 1; fi

# build docset
appledoc \
--project-name Redbeard \
--project-company "Redbeard Services Ltd" \
--project-version $1 \
--company-id io.redbeard \
--print-settings \
--output $docsets \
--templates $appledocTemplateDir \
--docset-install-path $docsets \
$frameworkPath

# copy icons, add fallback url and keyword to Info.plist
cp $iconPath/icon* $docsets/io.redbeard.Redbeard.docset/
plutil -insert "DashDocSetFallbackURL" -string "http://www.redbeard.io/files/documentation/api/v1/index.html" $docsets/io.redbeard.Redbeard.docset/Contents/Info.plist
plutil -insert "DocSetPlatformFamily" -string "redbeard" $docsets/io.redbeard.Redbeard.docset/Contents/Info.plist

# create tar archive
cd $docsets
tar --exclude='.DS_Store' -cvzf io.redbeard.Redbeard.tgz io.redbeard.Redbeard.docset
cd -
