#!/bin/bash

docsets=~/DocSets
frameworkPath=. # just call it from inside Redbeard.framework/
iconPath=../ # path for the icon.png and icon@2.png

usage() {
   echo "Usage:"
   echo " `basename $0` version"
}

# version must be provided
if [ $# -lt 1 ]; then usage && exit 1; fi

# build docset
appledoc \
--project-name Redbeard \
--project-company "Redbeard Services Ltd" \
--project-version $1 \
--company-id io.redbeard \
--print-settings \
--output $docsets \
--templates ~/Library/Application\ Support/appledoc \
--docset-install-path $docsets \
$frameworkPath

# copy icons and add fallback url to Info.plist
cp $iconPath/icon* $docsets/io.redbeard.Redbeard.docset/
plutil -insert "DashDocSetFallbackURL" -string "http://www.redbeard.io/files/documentation/api/v1/index.html" $docsets/io.redbeard.Redbeard.docset/Contents/Info.plist

# create tar archive
cd $docsets
tar --exclude='.DS_Store' -cvzf io.redbeard.Redbeard.tgz io.redbeard.Redbeard.docset
cd -
